In [1]:
# import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Import and read the dataset
dataset = pd.read_csv("Data.csv")
# Storing values of dependent and independent attributes 
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [6]:
# Splitting the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [8]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [9]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [10]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [11]:
# Fitting the model to the data as well as training it
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# creating an object for polynomial regression with degree 4
poly_reg = PolynomialFeatures(degree = 4)

# fitting the model to the training data and also transforming it
X_poly = poly_reg.fit_transform(X_train)

# creating an object for linear regression too
regressor = LinearRegression()

# fitting the regressor object
regressor.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# predicting the test set results. The predicted results will be printed along with the actual values.
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


In [13]:
# calculating the R^2 score which can be compared with the scores of other models
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9458192606428238