In [19]:
# import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
# import and read the dataset
dataset = pd.read_csv("Data.csv")

# store the values of dependent and independent variables separately
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [21]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [22]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [23]:
# reshape the values in y
y = y.reshape(len(y), 1)

In [24]:
# split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [25]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [26]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [27]:
print(y_train)

[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]


In [28]:
print(y_test)

[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


In [29]:
# In Support Vector Regression it is neccessary to implement Feature Scaling
from sklearn.preprocessing import StandardScaler

# create objects
sc_X = StandardScaler()
sc_y = StandardScaler()

# fit the object to the training set and transform
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [30]:
print(X_train)

[[-1.14 -0.89  0.67  0.52]
 [-0.81 -0.01  0.45  0.15]
 [ 1.77  1.85  0.24 -1.88]
 ...
 [-0.38 -1.25  0.85  0.13]
 [-0.92 -1.04  1.55  0.88]
 [ 1.7   1.06 -1.2  -2.42]]


In [31]:
print(y_train)

[[ 1.15]
 [ 0.8 ]
 [-1.31]
 ...
 [ 0.28]
 [ 0.49]
 [-1.54]]


In [32]:
# applying the SVR model to the training set and training the model as well
from sklearn.svm import SVR

# create the object of the function
regressor = SVR(kernel = 'rbf')

# fitting the model
regressor.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [33]:
# predicting the test set results and printing them alongside the actual test set values
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


In [34]:
# Calculating the R^2 score to get the value.
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9480784049986258