In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# read the csv file
dataset = pd.read_csv("Data.csv")

#split into two datasets
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [5]:
# Split into train and test datasets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=0)

In [6]:
print(X_train)

[[  22.74   58.41 1013.92   84.03]
 [  22.24   41.1  1001.96   42.6 ]
 [  16.73   39.64 1008.94   74.91]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [7]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  25.15   68.51 1013.25   72.31]
 [  20.47   58.16 1016.97   68.6 ]
 [  29.22   73.18 1012.22   64.91]]


In [8]:
print(y_train)

[447.85 451.95 464.46 ... 459.01 462.72 428.12]


In [9]:
print(y_test)

[431.23 460.01 461.14 ... 440.96 453.99 430.57]


In [10]:
# Deterimine the model
from sklearn.linear_model import LinearRegression

# create the object
regressor = LinearRegression()

# fit operation
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
# store the predicted values in a variable
y_pred = regressor.predict(X_test)

# Print values only upto 2 decimal places
np.set_printoptions(precision=2)

# The predictions of the train and test datasets should be printed together
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.61 431.23]
 [458.92 460.01]
 [463.08 461.14]
 ...
 [440.54 440.96]
 [452.98 453.99]
 [432.58 430.57]]


In [12]:
# Find coefficients and intercept
print(regressor.coef_)
print(regressor.intercept_)

[-1.92 -0.25  0.1  -0.15]
419.5271894506773


In [ ]:
# The equation can be written as
PE = 419.53 + (-1.92)*AT + (-0.25)*V + (0.1)*AP + (-0.15)*RH

In [14]:
# Evaluating the accuracy using R^2 score
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9289583408624013